
CREATE TABLE `trans_account_201907` (
  `id` BIGINT(20) NOT NULL,
  `exp_no` VARCHAR(50) DEFAULT NULL COMMENT '标准单据号',
  `exp_detail_no` VARCHAR(50) NOT NULL COMMENT '明细表主键ID',
  `exp_date` VARCHAR(50) NOT NULL COMMENT '计费日期',
  `system_source` VARCHAR(20) NOT NULL COMMENT '来源系统编码',
  `system_source_name` VARCHAR(60) DEFAULT NULL COMMENT '来源系统编码名称',
  `order_type` VARCHAR(20) NOT NULL COMMENT '来源单据类型编码',
  `order_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源单据类型名称',
  `transaction_type` VARCHAR(20) NOT NULL COMMENT '来源交易类型编码',
  `transaction_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源交易类型名称',
  `business_no` VARCHAR(50) NOT NULL COMMENT '业务单号',
  `cost_no` VARCHAR(50) NOT NULL COMMENT '费用项编码',
  `stragy_no` VARCHAR(50) NOT NULL COMMENT '定价策略编码',
  `stragy_version` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '定价策略版本',
  `price_base_no` VARCHAR(50) DEFAULT NULL COMMENT '标准价目表编码',
  `price_seller_no` VARCHAR(50) NOT NULL COMMENT '商家价目表编码',
  `ratio_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0.不区分，1.泡货，2.重货',
  `seller_no` VARCHAR(50) NOT NULL COMMENT '商家编码',
  `seller_name` VARCHAR(60) DEFAULT NULL COMMENT '商家名称',
  `bu_no` VARCHAR(50) DEFAULT NULL COMMENT '事业部编号',
  `bu_name` VARCHAR(60) DEFAULT NULL COMMENT '事业部名称',
  `shop_no` VARCHAR(50) DEFAULT NULL COMMENT '店铺编号',
  `shop_name` VARCHAR(60) DEFAULT NULL COMMENT '店铺名称',
  `start_address` VARCHAR(255) DEFAULT NULL COMMENT '起始地址',
  `end_address` VARCHAR(255) DEFAULT NULL COMMENT '目的地址',
  `amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '原金额',
  `actual_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '实收金额',
  `discount_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '折扣金额',
  `min_amount` DECIMAL(10,4) DEFAULT NULL COMMENT '最低收费',
  `qty` INT(11) DEFAULT '0' COMMENT '总件数',
  `qty_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总件数单价',
  `piece_type` TINYINT(4) DEFAULT NULL COMMENT '件型',
  `weight` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量',
  `weight_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量单价',
  `volume` DECIMAL(18,4) DEFAULT '0.0000' COMMENT '总体积',
  `volume_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总体积单价',
  `area` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积',
  `area_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积单价',
  `broad` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数',
  `broad_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数单价',
  `carton` INT(11) DEFAULT NULL COMMENT '总箱数',
  `carton_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总箱数单价',
  `pay_mode` TINYINT(4) DEFAULT NULL COMMENT '支付方式 在线支付、货到付款',
  `extend_msg` VARCHAR(1000) DEFAULT NULL,
  `transport_mode` TINYINT(4) DEFAULT NULL COMMENT '运输方式 公路运输、海运、空运',
  `collect_item_id` BIGINT(20) DEFAULT NULL,
  `batch_no` BIGINT(20) DEFAULT NULL,
  `collect_no` VARCHAR(50) DEFAULT NULL,
  `remark` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1、初始化/2、已计算 3失败',
  `charge_flag` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0:收费 1:免费',
  `charge_describe` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '费用描述',
  `finance_mark` VARCHAR(200) NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' COMMENT '计费打标',
  `overdue_day_num` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '超期天数',
  `store_start_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '存储开始时间',
  `is_delete` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1未删除0删除',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
  `update_user` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `start_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '起始配送中心号',
  `start_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '起始转运中心代码',
  `start_store_code` VARCHAR(50) DEFAULT NULL COMMENT '起始仓库号',
  `start_one_address` VARCHAR(50) DEFAULT NULL COMMENT '起始省',
  `start_two_address` VARCHAR(50) DEFAULT NULL COMMENT '起始市',
  `start_three_address` VARCHAR(50) DEFAULT NULL COMMENT '起始县',
  `start_four_address` VARCHAR(50) DEFAULT NULL COMMENT '起始镇',
  `end_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '目的配送中心号',
  `end_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '目的转运中心代码',
  `end_store_code` VARCHAR(50) DEFAULT NULL COMMENT '目的仓库号',
  `end_one_address` VARCHAR(50) DEFAULT NULL COMMENT '目的省',
  `end_two_address` VARCHAR(50) DEFAULT NULL COMMENT '目的市',
  `end_three_address` VARCHAR(50) DEFAULT NULL COMMENT '目的县',
  `end_four_address` VARCHAR(50) DEFAULT NULL COMMENT '目的镇',
  `goods_no` VARCHAR(50) DEFAULT NULL COMMENT 'SKU编码',
  `goods_fee_type` VARCHAR(50) DEFAULT NULL COMMENT '商品计费类别',
  `exp_month` VARCHAR(50) DEFAULT NULL COMMENT '计费月份',
  `buyer_erp` VARCHAR(50) DEFAULT NULL COMMENT '采购员erp',
  `buyer_name` VARCHAR(50) DEFAULT NULL COMMENT '采购员名称',
  `sale_erp` VARCHAR(50) DEFAULT NULL COMMENT '销售员erp',
  `sale_name` VARCHAR(50) DEFAULT NULL COMMENT '销售员名称',
  `business_from_no` VARCHAR(50) DEFAULT NULL COMMENT '来源单据号',
  `adjust_mny` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '调整金额',
  `business_from_no2` VARCHAR(50) DEFAULT NULL COMMENT '业务单来源单号2',
  `is_balance` TINYINT(4) UNSIGNED DEFAULT NULL,
  `bill_balance_no` VARCHAR(20) DEFAULT NULL,
  `weightUnit` DECIMAL(10,0) DEFAULT NULL COMMENT '续重单位量',
  `standard_collect_no` VARCHAR(100) DEFAULT NULL COMMENT '汇总单单号',
  `compute_source_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0标准单计费结果，1汇总单计费结果',
  `account_version` BIGINT(24) DEFAULT NULL,
  `error_msg` VARCHAR(255) DEFAULT NULL,
  `region` TINYINT(4) DEFAULT '0' COMMENT '区域',
  `exception_classify_code` TINYINT(4) DEFAULT '0' COMMENT '异常分类编码',
  `error_msg_code` TINYINT(4) DEFAULT '0' COMMENT '错误编码',
  `error_msg_record` VARCHAR(100) DEFAULT '' COMMENT '错误信息记录字段',
  `cost_type` TINYINT(1) DEFAULT '1' COMMENT '方向',
  `bms_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '接单中台关联id',
  `war_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '战区编码',
  `area_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '片区编码',
  `busi_dept_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '营业部编码',
  `org_one_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '一级部门编码，region太短不能用',
  `is_confirm` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '是否确认：0、未确认 1、已确认（默认值）',
  `is_reverse` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否被冲销：0、未被冲销（默认值）1、已被冲销',
  `reverse_trans_account_id` BIGINT(20) DEFAULT NULL COMMENT '被冲销的计费结果id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_expNo_expDetailNo_costNo_isdelete` (`exp_no`,`exp_detail_no`,`cost_no`,`is_delete`) USING BTREE,
  KEY `idx_expdate_sellerNo` (`exp_date`,`seller_no`,`system_source`,`cost_no`) USING BTREE,
  KEY `idx_standard_collect_no` (`standard_collect_no`) USING BTREE,
  KEY `idx_seller_no` (`seller_no`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `trans_account_201908` (
  `id` BIGINT(20) NOT NULL,
  `exp_no` VARCHAR(50) DEFAULT NULL COMMENT '标准单据号',
  `exp_detail_no` VARCHAR(50) NOT NULL COMMENT '明细表主键ID',
  `exp_date` VARCHAR(50) NOT NULL COMMENT '计费日期',
  `system_source` VARCHAR(20) NOT NULL COMMENT '来源系统编码',
  `system_source_name` VARCHAR(60) DEFAULT NULL COMMENT '来源系统编码名称',
  `order_type` VARCHAR(20) NOT NULL COMMENT '来源单据类型编码',
  `order_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源单据类型名称',
  `transaction_type` VARCHAR(20) NOT NULL COMMENT '来源交易类型编码',
  `transaction_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源交易类型名称',
  `business_no` VARCHAR(50) NOT NULL COMMENT '业务单号',
  `cost_no` VARCHAR(50) NOT NULL COMMENT '费用项编码',
  `stragy_no` VARCHAR(50) NOT NULL COMMENT '定价策略编码',
  `stragy_version` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '定价策略版本',
  `price_base_no` VARCHAR(50) DEFAULT NULL COMMENT '标准价目表编码',
  `price_seller_no` VARCHAR(50) NOT NULL COMMENT '商家价目表编码',
  `ratio_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0.不区分，1.泡货，2.重货',
  `seller_no` VARCHAR(50) NOT NULL COMMENT '商家编码',
  `seller_name` VARCHAR(60) DEFAULT NULL COMMENT '商家名称',
  `bu_no` VARCHAR(50) DEFAULT NULL COMMENT '事业部编号',
  `bu_name` VARCHAR(60) DEFAULT NULL COMMENT '事业部名称',
  `shop_no` VARCHAR(50) DEFAULT NULL COMMENT '店铺编号',
  `shop_name` VARCHAR(60) DEFAULT NULL COMMENT '店铺名称',
  `start_address` VARCHAR(255) DEFAULT NULL COMMENT '起始地址',
  `end_address` VARCHAR(255) DEFAULT NULL COMMENT '目的地址',
  `amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '原金额',
  `actual_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '实收金额',
  `discount_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '折扣金额',
  `min_amount` DECIMAL(10,4) DEFAULT NULL COMMENT '最低收费',
  `qty` INT(11) DEFAULT '0' COMMENT '总件数',
  `qty_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总件数单价',
  `piece_type` TINYINT(4) DEFAULT NULL COMMENT '件型',
  `weight` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量',
  `weight_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量单价',
  `volume` DECIMAL(18,4) DEFAULT '0.0000' COMMENT '总体积',
  `volume_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总体积单价',
  `area` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积',
  `area_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积单价',
  `broad` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数',
  `broad_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数单价',
  `carton` INT(11) DEFAULT NULL COMMENT '总箱数',
  `carton_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总箱数单价',
  `pay_mode` TINYINT(4) DEFAULT NULL COMMENT '支付方式 在线支付、货到付款',
  `extend_msg` VARCHAR(1000) DEFAULT NULL,
  `transport_mode` TINYINT(4) DEFAULT NULL COMMENT '运输方式 公路运输、海运、空运',
  `collect_item_id` BIGINT(20) DEFAULT NULL,
  `batch_no` BIGINT(20) DEFAULT NULL,
  `collect_no` VARCHAR(50) DEFAULT NULL,
  `remark` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1、初始化/2、已计算 3失败',
  `charge_flag` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0:收费 1:免费',
  `charge_describe` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '费用描述',
  `finance_mark` VARCHAR(200) NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' COMMENT '计费打标',
  `overdue_day_num` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '超期天数',
  `store_start_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '存储开始时间',
  `is_delete` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1未删除0删除',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
  `update_user` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `start_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '起始配送中心号',
  `start_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '起始转运中心代码',
  `start_store_code` VARCHAR(50) DEFAULT NULL COMMENT '起始仓库号',
  `start_one_address` VARCHAR(50) DEFAULT NULL COMMENT '起始省',
  `start_two_address` VARCHAR(50) DEFAULT NULL COMMENT '起始市',
  `start_three_address` VARCHAR(50) DEFAULT NULL COMMENT '起始县',
  `start_four_address` VARCHAR(50) DEFAULT NULL COMMENT '起始镇',
  `end_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '目的配送中心号',
  `end_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '目的转运中心代码',
  `end_store_code` VARCHAR(50) DEFAULT NULL COMMENT '目的仓库号',
  `end_one_address` VARCHAR(50) DEFAULT NULL COMMENT '目的省',
  `end_two_address` VARCHAR(50) DEFAULT NULL COMMENT '目的市',
  `end_three_address` VARCHAR(50) DEFAULT NULL COMMENT '目的县',
  `end_four_address` VARCHAR(50) DEFAULT NULL COMMENT '目的镇',
  `goods_no` VARCHAR(50) DEFAULT NULL COMMENT 'SKU编码',
  `goods_fee_type` VARCHAR(50) DEFAULT NULL COMMENT '商品计费类别',
  `exp_month` VARCHAR(50) DEFAULT NULL COMMENT '计费月份',
  `buyer_erp` VARCHAR(50) DEFAULT NULL COMMENT '采购员erp',
  `buyer_name` VARCHAR(50) DEFAULT NULL COMMENT '采购员名称',
  `sale_erp` VARCHAR(50) DEFAULT NULL COMMENT '销售员erp',
  `sale_name` VARCHAR(50) DEFAULT NULL COMMENT '销售员名称',
  `business_from_no` VARCHAR(50) DEFAULT NULL COMMENT '来源单据号',
  `adjust_mny` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '调整金额',
  `business_from_no2` VARCHAR(50) DEFAULT NULL COMMENT '业务单来源单号2',
  `is_balance` TINYINT(4) UNSIGNED DEFAULT NULL,
  `bill_balance_no` VARCHAR(20) DEFAULT NULL,
  `weightUnit` DECIMAL(10,0) DEFAULT NULL COMMENT '续重单位量',
  `standard_collect_no` VARCHAR(100) DEFAULT NULL COMMENT '汇总单单号',
  `compute_source_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0标准单计费结果，1汇总单计费结果',
  `account_version` BIGINT(24) DEFAULT NULL,
  `error_msg` VARCHAR(255) DEFAULT NULL,
  `region` TINYINT(4) DEFAULT '0' COMMENT '区域',
  `exception_classify_code` TINYINT(4) DEFAULT '0' COMMENT '异常分类编码',
  `error_msg_code` TINYINT(4) DEFAULT '0' COMMENT '错误编码',
  `error_msg_record` VARCHAR(100) DEFAULT '' COMMENT '错误信息记录字段',
  `cost_type` TINYINT(1) DEFAULT '1' COMMENT '方向',
  `bms_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '接单中台关联id',
  `war_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '战区编码',
  `area_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '片区编码',
  `busi_dept_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '营业部编码',
  `org_one_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '一级部门编码，region太短不能用',
  `is_confirm` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '是否确认：0、未确认 1、已确认（默认值）',
  `is_reverse` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否被冲销：0、未被冲销（默认值）1、已被冲销',
  `reverse_trans_account_id` BIGINT(20) DEFAULT NULL COMMENT '被冲销的计费结果id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_expNo_expDetailNo_costNo_isdelete` (`exp_no`,`exp_detail_no`,`cost_no`,`is_delete`) USING BTREE,
  KEY `idx_expdate_sellerNo` (`exp_date`,`seller_no`,`system_source`,`cost_no`) USING BTREE,
  KEY `idx_standard_collect_no` (`standard_collect_no`) USING BTREE,
  KEY `idx_seller_no` (`seller_no`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `trans_account_202007` (
  `id` BIGINT(20) NOT NULL,
  `exp_no` VARCHAR(50) DEFAULT NULL COMMENT '标准单据号',
  `exp_detail_no` VARCHAR(50) NOT NULL COMMENT '明细表主键ID',
  `exp_date` VARCHAR(50) NOT NULL COMMENT '计费日期',
  `system_source` VARCHAR(20) NOT NULL COMMENT '来源系统编码',
  `system_source_name` VARCHAR(60) DEFAULT NULL COMMENT '来源系统编码名称',
  `order_type` VARCHAR(20) NOT NULL COMMENT '来源单据类型编码',
  `order_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源单据类型名称',
  `transaction_type` VARCHAR(20) NOT NULL COMMENT '来源交易类型编码',
  `transaction_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源交易类型名称',
  `business_no` VARCHAR(50) NOT NULL COMMENT '业务单号',
  `cost_no` VARCHAR(50) NOT NULL COMMENT '费用项编码',
  `stragy_no` VARCHAR(50) NOT NULL COMMENT '定价策略编码',
  `stragy_version` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '定价策略版本',
  `price_base_no` VARCHAR(50) DEFAULT NULL COMMENT '标准价目表编码',
  `price_seller_no` VARCHAR(50) NOT NULL COMMENT '商家价目表编码',
  `ratio_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0.不区分，1.泡货，2.重货',
  `seller_no` VARCHAR(50) NOT NULL COMMENT '商家编码',
  `seller_name` VARCHAR(60) DEFAULT NULL COMMENT '商家名称',
  `bu_no` VARCHAR(50) DEFAULT NULL COMMENT '事业部编号',
  `bu_name` VARCHAR(60) DEFAULT NULL COMMENT '事业部名称',
  `shop_no` VARCHAR(50) DEFAULT NULL COMMENT '店铺编号',
  `shop_name` VARCHAR(60) DEFAULT NULL COMMENT '店铺名称',
  `start_address` VARCHAR(255) DEFAULT NULL COMMENT '起始地址',
  `end_address` VARCHAR(255) DEFAULT NULL COMMENT '目的地址',
  `amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '原金额',
  `actual_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '实收金额',
  `discount_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '折扣金额',
  `min_amount` DECIMAL(10,4) DEFAULT NULL COMMENT '最低收费',
  `qty` INT(11) DEFAULT '0' COMMENT '总件数',
  `qty_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总件数单价',
  `piece_type` TINYINT(4) DEFAULT NULL COMMENT '件型',
  `weight` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量',
  `weight_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量单价',
  `volume` DECIMAL(18,4) DEFAULT '0.0000' COMMENT '总体积',
  `volume_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总体积单价',
  `area` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积',
  `area_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积单价',
  `broad` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数',
  `broad_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数单价',
  `carton` INT(11) DEFAULT NULL COMMENT '总箱数',
  `carton_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总箱数单价',
  `pay_mode` TINYINT(4) DEFAULT NULL COMMENT '支付方式 在线支付、货到付款',
  `extend_msg` VARCHAR(1000) DEFAULT NULL,
  `transport_mode` TINYINT(4) DEFAULT NULL COMMENT '运输方式 公路运输、海运、空运',
  `collect_item_id` BIGINT(20) DEFAULT NULL,
  `batch_no` BIGINT(20) DEFAULT NULL,
  `collect_no` VARCHAR(50) DEFAULT NULL,
  `remark` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1、初始化/2、已计算 3失败',
  `charge_flag` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0:收费 1:免费',
  `charge_describe` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '费用描述',
  `finance_mark` VARCHAR(200) NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' COMMENT '计费打标',
  `overdue_day_num` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '超期天数',
  `store_start_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '存储开始时间',
  `is_delete` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1未删除0删除',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
  `update_user` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `start_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '起始配送中心号',
  `start_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '起始转运中心代码',
  `start_store_code` VARCHAR(50) DEFAULT NULL COMMENT '起始仓库号',
  `start_one_address` VARCHAR(50) DEFAULT NULL COMMENT '起始省',
  `start_two_address` VARCHAR(50) DEFAULT NULL COMMENT '起始市',
  `start_three_address` VARCHAR(50) DEFAULT NULL COMMENT '起始县',
  `start_four_address` VARCHAR(50) DEFAULT NULL COMMENT '起始镇',
  `end_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '目的配送中心号',
  `end_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '目的转运中心代码',
  `end_store_code` VARCHAR(50) DEFAULT NULL COMMENT '目的仓库号',
  `end_one_address` VARCHAR(50) DEFAULT NULL COMMENT '目的省',
  `end_two_address` VARCHAR(50) DEFAULT NULL COMMENT '目的市',
  `end_three_address` VARCHAR(50) DEFAULT NULL COMMENT '目的县',
  `end_four_address` VARCHAR(50) DEFAULT NULL COMMENT '目的镇',
  `goods_no` VARCHAR(50) DEFAULT NULL COMMENT 'SKU编码',
  `goods_fee_type` VARCHAR(50) DEFAULT NULL COMMENT '商品计费类别',
  `exp_month` VARCHAR(50) DEFAULT NULL COMMENT '计费月份',
  `buyer_erp` VARCHAR(50) DEFAULT NULL COMMENT '采购员erp',
  `buyer_name` VARCHAR(50) DEFAULT NULL COMMENT '采购员名称',
  `sale_erp` VARCHAR(50) DEFAULT NULL COMMENT '销售员erp',
  `sale_name` VARCHAR(50) DEFAULT NULL COMMENT '销售员名称',
  `business_from_no` VARCHAR(50) DEFAULT NULL COMMENT '来源单据号',
  `adjust_mny` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '调整金额',
  `business_from_no2` VARCHAR(50) DEFAULT NULL COMMENT '业务单来源单号2',
  `is_balance` TINYINT(4) UNSIGNED DEFAULT NULL,
  `bill_balance_no` VARCHAR(20) DEFAULT NULL,
  `weightUnit` DECIMAL(10,0) DEFAULT NULL COMMENT '续重单位量',
  `standard_collect_no` VARCHAR(100) DEFAULT NULL COMMENT '汇总单单号',
  `compute_source_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0标准单计费结果，1汇总单计费结果',
  `account_version` BIGINT(24) DEFAULT NULL,
  `error_msg` VARCHAR(255) DEFAULT NULL,
  `region` TINYINT(4) DEFAULT '0' COMMENT '区域',
  `exception_classify_code` TINYINT(4) DEFAULT '0' COMMENT '异常分类编码',
  `error_msg_code` TINYINT(4) DEFAULT '0' COMMENT '错误编码',
  `error_msg_record` VARCHAR(100) DEFAULT '' COMMENT '错误信息记录字段',
  `cost_type` TINYINT(1) DEFAULT '1' COMMENT '方向',
  `bms_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '接单中台关联id',
  `war_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '战区编码',
  `area_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '片区编码',
  `busi_dept_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '营业部编码',
  `org_one_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '一级部门编码，region太短不能用',
  `is_confirm` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '是否确认：0、未确认 1、已确认（默认值）',
  `is_reverse` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否被冲销：0、未被冲销（默认值）1、已被冲销',
  `reverse_trans_account_id` BIGINT(20) DEFAULT NULL COMMENT '被冲销的计费结果id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_expNo_expDetailNo_costNo_isdelete` (`exp_no`,`exp_detail_no`,`cost_no`,`is_delete`) USING BTREE,
  KEY `idx_expdate_sellerNo` (`exp_date`,`seller_no`,`system_source`,`cost_no`) USING BTREE,
  KEY `idx_standard_collect_no` (`standard_collect_no`) USING BTREE,
  KEY `idx_seller_no` (`seller_no`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `trans_account_202008` (
  `id` BIGINT(20) NOT NULL,
  `exp_no` VARCHAR(50) DEFAULT NULL COMMENT '标准单据号',
  `exp_detail_no` VARCHAR(50) NOT NULL COMMENT '明细表主键ID',
  `exp_date` VARCHAR(50) NOT NULL COMMENT '计费日期',
  `system_source` VARCHAR(20) NOT NULL COMMENT '来源系统编码',
  `system_source_name` VARCHAR(60) DEFAULT NULL COMMENT '来源系统编码名称',
  `order_type` VARCHAR(20) NOT NULL COMMENT '来源单据类型编码',
  `order_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源单据类型名称',
  `transaction_type` VARCHAR(20) NOT NULL COMMENT '来源交易类型编码',
  `transaction_type_name` VARCHAR(60) DEFAULT NULL COMMENT '来源交易类型名称',
  `business_no` VARCHAR(50) NOT NULL COMMENT '业务单号',
  `cost_no` VARCHAR(50) NOT NULL COMMENT '费用项编码',
  `stragy_no` VARCHAR(50) NOT NULL COMMENT '定价策略编码',
  `stragy_version` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '定价策略版本',
  `price_base_no` VARCHAR(50) DEFAULT NULL COMMENT '标准价目表编码',
  `price_seller_no` VARCHAR(50) NOT NULL COMMENT '商家价目表编码',
  `ratio_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0.不区分，1.泡货，2.重货',
  `seller_no` VARCHAR(50) NOT NULL COMMENT '商家编码',
  `seller_name` VARCHAR(60) DEFAULT NULL COMMENT '商家名称',
  `bu_no` VARCHAR(50) DEFAULT NULL COMMENT '事业部编号',
  `bu_name` VARCHAR(60) DEFAULT NULL COMMENT '事业部名称',
  `shop_no` VARCHAR(50) DEFAULT NULL COMMENT '店铺编号',
  `shop_name` VARCHAR(60) DEFAULT NULL COMMENT '店铺名称',
  `start_address` VARCHAR(255) DEFAULT NULL COMMENT '起始地址',
  `end_address` VARCHAR(255) DEFAULT NULL COMMENT '目的地址',
  `amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '原金额',
  `actual_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '实收金额',
  `discount_amount` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '折扣金额',
  `min_amount` DECIMAL(10,4) DEFAULT NULL COMMENT '最低收费',
  `qty` INT(11) DEFAULT '0' COMMENT '总件数',
  `qty_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总件数单价',
  `piece_type` TINYINT(4) DEFAULT NULL COMMENT '件型',
  `weight` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量',
  `weight_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总重量单价',
  `volume` DECIMAL(18,4) DEFAULT '0.0000' COMMENT '总体积',
  `volume_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总体积单价',
  `area` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积',
  `area_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总面积单价',
  `broad` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数',
  `broad_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总板数单价',
  `carton` INT(11) DEFAULT NULL COMMENT '总箱数',
  `carton_price` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '总箱数单价',
  `pay_mode` TINYINT(4) DEFAULT NULL COMMENT '支付方式 在线支付、货到付款',
  `extend_msg` VARCHAR(1000) DEFAULT NULL,
  `transport_mode` TINYINT(4) DEFAULT NULL COMMENT '运输方式 公路运输、海运、空运',
  `collect_item_id` BIGINT(20) DEFAULT NULL,
  `batch_no` BIGINT(20) DEFAULT NULL,
  `collect_no` VARCHAR(50) DEFAULT NULL,
  `remark` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1、初始化/2、已计算 3失败',
  `charge_flag` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0:收费 1:免费',
  `charge_describe` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '费用描述',
  `finance_mark` VARCHAR(200) NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' COMMENT '计费打标',
  `overdue_day_num` DECIMAL(10,4) NOT NULL DEFAULT '0.0000' COMMENT '超期天数',
  `store_start_time` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '存储开始时间',
  `is_delete` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1未删除0删除',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  `create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
  `update_user` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `start_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '起始配送中心号',
  `start_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '起始转运中心代码',
  `start_store_code` VARCHAR(50) DEFAULT NULL COMMENT '起始仓库号',
  `start_one_address` VARCHAR(50) DEFAULT NULL COMMENT '起始省',
  `start_two_address` VARCHAR(50) DEFAULT NULL COMMENT '起始市',
  `start_three_address` VARCHAR(50) DEFAULT NULL COMMENT '起始县',
  `start_four_address` VARCHAR(50) DEFAULT NULL COMMENT '起始镇',
  `end_cky_code` VARCHAR(50) DEFAULT NULL COMMENT '目的配送中心号',
  `end_trans_center_code` VARCHAR(50) DEFAULT NULL COMMENT '目的转运中心代码',
  `end_store_code` VARCHAR(50) DEFAULT NULL COMMENT '目的仓库号',
  `end_one_address` VARCHAR(50) DEFAULT NULL COMMENT '目的省',
  `end_two_address` VARCHAR(50) DEFAULT NULL COMMENT '目的市',
  `end_three_address` VARCHAR(50) DEFAULT NULL COMMENT '目的县',
  `end_four_address` VARCHAR(50) DEFAULT NULL COMMENT '目的镇',
  `goods_no` VARCHAR(50) DEFAULT NULL COMMENT 'SKU编码',
  `goods_fee_type` VARCHAR(50) DEFAULT NULL COMMENT '商品计费类别',
  `exp_month` VARCHAR(50) DEFAULT NULL COMMENT '计费月份',
  `buyer_erp` VARCHAR(50) DEFAULT NULL COMMENT '采购员erp',
  `buyer_name` VARCHAR(50) DEFAULT NULL COMMENT '采购员名称',
  `sale_erp` VARCHAR(50) DEFAULT NULL COMMENT '销售员erp',
  `sale_name` VARCHAR(50) DEFAULT NULL COMMENT '销售员名称',
  `business_from_no` VARCHAR(50) DEFAULT NULL COMMENT '来源单据号',
  `adjust_mny` DECIMAL(10,4) DEFAULT '0.0000' COMMENT '调整金额',
  `business_from_no2` VARCHAR(50) DEFAULT NULL COMMENT '业务单来源单号2',
  `is_balance` TINYINT(4) UNSIGNED DEFAULT NULL,
  `bill_balance_no` VARCHAR(20) DEFAULT NULL,
  `weightUnit` DECIMAL(10,0) DEFAULT NULL COMMENT '续重单位量',
  `standard_collect_no` VARCHAR(100) DEFAULT NULL COMMENT '汇总单单号',
  `compute_source_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0标准单计费结果，1汇总单计费结果',
  `account_version` BIGINT(24) DEFAULT NULL,
  `error_msg` VARCHAR(255) DEFAULT NULL,
  `region` TINYINT(4) DEFAULT '0' COMMENT '区域',
  `exception_classify_code` TINYINT(4) DEFAULT '0' COMMENT '异常分类编码',
  `error_msg_code` TINYINT(4) DEFAULT '0' COMMENT '错误编码',
  `error_msg_record` VARCHAR(100) DEFAULT '' COMMENT '错误信息记录字段',
  `cost_type` TINYINT(1) DEFAULT '1' COMMENT '方向',
  `bms_id` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '接单中台关联id',
  `war_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '战区编码',
  `area_zone_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '片区编码',
  `busi_dept_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '营业部编码',
  `org_one_code` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '一级部门编码，region太短不能用',
  `is_confirm` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '是否确认：0、未确认 1、已确认（默认值）',
  `is_reverse` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '是否被冲销：0、未被冲销（默认值）1、已被冲销',
  `reverse_trans_account_id` BIGINT(20) DEFAULT NULL COMMENT '被冲销的计费结果id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_expNo_expDetailNo_costNo_isdelete` (`exp_no`,`exp_detail_no`,`cost_no`,`is_delete`) USING BTREE,
  KEY `idx_expdate_sellerNo` (`exp_date`,`seller_no`,`system_source`,`cost_no`) USING BTREE,
  KEY `idx_standard_collect_no` (`standard_collect_no`) USING BTREE,
  KEY `idx_seller_no` (`seller_no`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

